stages:
    - assets
    - pages

.assets: &assets
    stage: assets
    image: node:16.4.2-alpine
    script:
        - npm install
        - BASE_URL=${BASE_URL} node_modules/.bin/encore production
    artifacts:
        paths:
            - public
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - node_modules/

.generate: &generate
    stage: pages
    image: jakzal/phpqa:php8.0-alpine
    script:
        - mkdir -p node_modules
        - composer install
        - make build
    artifacts:
        paths:
            - public
    cache:
        key:
            files:
                - composer.lock
        paths:
            - vendor/

preview-assets:
    <<: *assets
    variables:
        # TODO: simplify with https://gitlab.com/gitlab-org/gitlab/-/issues/36373
        BASE_URL: https://${CI_PROJECT_ROOT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/engineering/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public
    except:
        - main
        - master
preview:
    <<: *generate
    needs:
        - preview-assets
    variables:
        # TODO: simplify with https://gitlab.com/gitlab-org/gitlab/-/issues/36373
        BASE_URL: https://${CI_PROJECT_ROOT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/engineering/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public
    except:
        - main
        - master

pages-assets:
    <<: *assets
    variables:
        BASE_URL: ${CI_PAGES_URL}
    only:
        - main
        - master
pages:
    <<: *generate
    needs:
        - pages-assets
    variables:
        BASE_URL: ${CI_PAGES_URL}
    only:
        - main
        - master
